In [1]:
import pandas as pd


flight_df = pd.read_csv('./winter_2021_clean.csv')

departure_df = flight_df.groupby('departure_icao').agg(num_flights = ('departure_iata','count')).sort_values(by = 'num_flights').reset_index()

arrival_df = flight_df.groupby('arrival_icao').agg(num_flights = ('departure_iata','count')).sort_values(by = 'num_flights').reset_index()

# departure_df.merge(arrival_df, )
# departure_df
res = departure_df.merge(arrival_df, left_on='departure_icao', right_on='arrival_icao')
res['flight_all'] = res['num_flights_x'] + res['num_flights_y']
res = res.sort_values('flight_all')
res.tail(70)

res = res['departure_icao'].tail(80).to_list()
len(res)

80

In [59]:
airport_df = pd.read_csv('airport_clean.csv')
# arrival_df[arrival_df['arrival_icao']]
overall_res = airport_df[airport_df['icao_code'].isin(res)]
# res.to_csv('|airport_important.csv')

In [61]:
overall_res.to_csv('airport_important.csv')

In [3]:
departure_iata_list =list(flight_df.departure_iata.value_counts().index)
arrival_iata_list = list(flight_df.arrival_iata.value_counts().index)

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_gate,departure_delay,departure_scheduled,departure_estimated,...,arrival_estimated,arrival_actual,arrival_estimated_runway,arrival_actual_runway,airline_name,airline_iata,airline_icao,flight_number,flight_iata,flight_icao
0,2021-12-06,landed,John F Kennedy International,America/New_York,JFK,KJFK,35,35.0,2021-12-06 16:35:00+00:00,2021-12-06 16:35:00+00:00,...,2021-12-06 19:55:00+00:00,2021-12-06 20:27:00+00:00,2021-12-06 20:27:00+00:00,2021-12-06 20:27:00+00:00,American Airlines,AA,AAL,429.0,AA429,AAL429
1,2021-12-06,landed,John F Kennedy International,America/New_York,JFK,KJFK,29,52.0,2021-12-06 16:30:00+00:00,2021-12-06 16:30:00+00:00,...,2021-12-06 19:37:00+00:00,2021-12-06 19:52:00+00:00,2021-12-06 19:52:00+00:00,2021-12-06 19:52:00+00:00,JetBlue Airways,B6,JBU,1401.0,B61401,JBU1401
2,2021-12-06,landed,John F Kennedy International,America/New_York,JFK,KJFK,17,34.0,2021-12-06 16:30:00+00:00,2021-12-06 16:30:00+00:00,...,2021-12-06 19:50:00+00:00,2021-12-06 19:53:00+00:00,2021-12-06 19:53:00+00:00,2021-12-06 19:53:00+00:00,JetBlue Airways,B6,JBU,263.0,B6263,JBU263
3,2021-12-06,landed,John F Kennedy International,America/New_York,JFK,KJFK,2,56.0,2021-12-06 16:30:00+00:00,2021-12-06 16:30:00+00:00,...,2021-12-07 05:50:00+00:00,2021-12-07 05:30:00+00:00,2021-12-07 05:30:00+00:00,2021-12-07 05:30:00+00:00,Air France,AF,AFR,23.0,AF23,AFR23
4,2021-12-06,landed,John F Kennedy International,America/New_York,JFK,KJFK,6,35.0,2021-12-06 16:30:00+00:00,2021-12-06 16:30:00+00:00,...,2021-12-06 20:01:00+00:00,2021-12-06 20:11:00+00:00,2021-12-06 20:11:00+00:00,2021-12-06 20:11:00+00:00,American Airlines,AA,AAL,306.0,AA306,AAL306
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93495,2022-02-28,landed,Greater Rochester International,America/New_York,ROC,KROC,B5,4.0,2022-02-28 13:00:00+00:00,2022-02-28 13:00:00+00:00,...,2022-02-28 14:29:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,Air France,AF,AFR,2894.0,AF2894,AFR2894
93496,2022-02-28,landed,Greater Rochester International,America/New_York,ROC,KROC,B5,4.0,2022-02-28 13:00:00+00:00,2022-02-28 13:00:00+00:00,...,2022-02-28 14:29:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,KLM,KL,KLM,5586.0,KL5586,KLM5586
93497,2022-02-28,landed,Greater Rochester International,America/New_York,ROC,KROC,B5,4.0,2022-02-28 13:00:00+00:00,2022-02-28 13:00:00+00:00,...,2022-02-28 14:29:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,Virgin Atlantic,VS,VIR,1674.0,VS1674,VIR1674
93498,2022-02-28,landed,Greater Rochester International,America/New_York,ROC,KROC,B5,4.0,2022-02-28 13:00:00+00:00,2022-02-28 13:00:00+00:00,...,2022-02-28 14:29:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,2022-02-28 14:04:00+00:00,Delta Air Lines,DL,DAL,5076.0,DL5076,DAL5076
93499,2022-02-28,landed,Greater Rochester International,America/New_York,ROC,KROC,A4,8.0,2022-02-28 13:00:00+00:00,2022-02-28 13:00:00+00:00,...,2022-02-28 14:15:00+00:00,2022-02-28 13:55:00+00:00,2022-02-28 13:55:00+00:00,2022-02-28 13:55:00+00:00,Southwest Airlines,WN,SWA,2416.0,WN2416,SWA2416

In [4]:
overall_iata_list  = set(departure_iata_list + arrival_iata_list)
len(overall_iata_list)

3636

In [13]:
airport_df = pd.read_csv('./airport_clean.csv')
airport_df

,Unnamed: 0,id,gmt,iata_code,city_iata_code,icao_code,country_iso2,geoname_id,latitude,longitude,airport_name,country_name
0,0,1,-10,AAA,AAA,NTGA,PF,6947726.0,-17.050,-145.417,Anaa,French Polynesia
1,1,2,10,AAB,AAB,YARY,AU,7730796.0,-26.700,141.042,Arrabury,Australia
2,2,3,2,AAC,AAC,HEAR,EG,6297289.0,31.133,33.750,El Arish International Airport,Egypt
3,4,5,-5,AAF,AAF,KAAF,US,4146153.0,29.733,-84.983,Apalachicola Regional,United States
4,5,6,-3,AAG,AAG,SSYA,BR,3471795.0,-24.104,-49.790,Arapoti,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...
5888,6467,10003,-6,ZWL,ZWL,CZWL,CA,7668170.0,58.100,-103.183,Wollaston Lake,Canada
5889,6469,10030,8,ZYI,ZYI,ZUZY,CN,8260946.0,27.667,106.833,Zunyi,China
5890,6470,10033,6,ZYL,ZYL,VGSY,BD,6301086.0,24.958,91.870,Osmani International,Bangladesh
5891,6471,10050,2,ZZU,ZZU,FWUU,MW,6297127.0,-11.443,34.013,Mzuzu,Malawi
5892,6472,10051,-5,ZZV,ZZV,KZZV,US,4528929.0,39.933,-82.017,Zanesville,United States

In [18]:
res = airport_df[airport_df['iata_code'].isin(overall_iata_list)]
res.drop(res.columns[0], axis=1,inplace=True)

/opt/homebrew/anaconda3/envs/cmpt733/lib/python3.7/site-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [20]:
res.to_csv('airport_cleaner.csv')

In [4]:
df = pd.read_csv('airport_cleaner.csv',)
df['iata_code'].value_counts()

AAF    1
PNA    1
PMF    1
PMG    1
PMI    1
      ..
HLP    1
HLZ    1
HMA    1
HMB    1
ZZV    1
Name: iata_code, Length: 3044, dtype: int64