In [ ]:
import requests
import pandas as pd
from datetime import date, timedelta
import numpy as np

In [ ]:
airport_df = pd.read_csv('./airport_cleaner.csv')
airport_df.shape

(3044, 12)

In [ ]:

data = []

for index, row in airport_df.iterrows():
    # 0 - 655
    # 656 - 1311
    # 1311- 1967
    # 1967 - 2622
    # 2622 - 3044
    if index>=0 and index<=163:
        one_data = []
        lat = row['latitude']
        lon = row['longitude']
        iata_code = row['iata_code']
        params = {
            'key': 'd9aedb8fc45342f7ac2d000204861195',
            'start_date': '2021-12-01',
            'end_date': '2022-03-01',
            'lat':  str(lat),
            'lon':  str(lon),


        }
        api_result = requests.get('https://api.weatherbit.io/v2.0/history/daily', params)
        print(index)
        try:
            if 'data' in api_result.json():
                api_response = api_result.json()['data']
                for cur_date in api_response:
                    part_df = pd.json_normalize(cur_date)
                    one_data.append(part_df)

                one_df = pd.concat(one_data)
                one_df['iata_code']=iata_code
                one_df['latitude'] = lat
                one_df['longitude'] = lon
                data.append(one_df)
            else:
                print(lat,lon,iata_code)
                print(api_result.json())
        except ValueError:  # includes simplejson.decoder.JSONDecodeError
            print(api_result)
            print(lat,lon,iata_code)
df = pd.concat(data)

df.to_csv('./weather_0_163.csv',index=False)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163