In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# 获取当前目录下的CSV文件名
def name(path):
    file_name = []
    # 将当前目录下的所有文件名称读取进来
    a = os.listdir(path)
    # a.sort()
    print(a)
    for j in a:
        # 判断是否为csv文件，如果是则存储到列表中
        if os.path.splitext(j)[1] == '.csv':
            file_name.append(j)
    return file_name

In [3]:
def dir_process(path, dirpath):
    file_name = name(path)
    df = pd.DataFrame()
    for fn in file_name:
        df = data_process(df, path + fn, dirpath)
    df.to_csv(dirpath)
    return

In [4]:
def data_process(df, path, dirpath):
    data = pd.read_csv(path)
    df = pd.concat([df, data])
    return df

In [5]:
dir_process('./0_655/', './weather.csv')

['weather_0_163.csv', 'weather_496_655.csv', '.DS_Store', 'weather_important1.csv', 'weather_1478_1495.csv', 'weather_1496_1534.csv', 'weather_2299_2337.csv', 'weather_1535_1574.csv', 'weather_1968_2133.csv', 'weather_2134_2299.csv', 'weather_164_329.csv', 'weather_330_495.csv', 'weather_2623_2660.csv', 'importairport38_74.csv', 'weather_2661_2698.csv', 'weather_1312_1477.csv']

In [6]:
weather = pd.read_csv('./weather.csv')
airport = pd.read_csv('./airport_cleaner.csv')
weather_airport = pd.merge(weather, airport, how='inner', on=['latitude', 'longitude']).drop(['Unnamed: 0_x','Unnamed: 0_y'], axis=1)
weather_airport.head(10)

,rh,max_wind_spd_ts,t_ghi,max_wind_spd,solar_rad,wind_gust_spd,max_temp_ts,min_temp_ts,clouds,max_dni,...,longitude,id,gmt,iata_code_y,city_iata_code,icao_code,country_iso2,geoname_id,airport_name,country_name
0,96.0,1638356400,616.4,11.8,2.7,11.8,1638334800,1638388800,100,516.2,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
1,83.1,1638399600,601.8,7.7,21.0,7.7,1638442800,1638482400,64,512.3,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
2,95.5,1638550800,588.1,4.6,2.5,4.6,1638550800,1638504000,97,508.6,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
3,93.6,1638655200,575.2,9.3,2.8,9.3,1638648000,1638619200,98,505.1,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
4,85.8,1638669600,563.0,8.2,4.8,8.2,1638662400,1638741600,99,501.6,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
5,82.5,1638824400,551.7,8.8,8.2,8.8,1638820800,1638759600,90,498.4,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
6,77.8,1638903600,541.2,9.8,4.4,9.8,1638896400,1638864000,100,495.3,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
7,86.9,1638946800,531.5,12.9,3.4,12.9,1638954000,1638972000,100,492.3,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
8,92.7,1639004400,522.6,6.7,2.4,6.7,1639058400,1639022400,98,489.6,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark
9,96.4,1639116000,514.4,4.6,5.2,4.6,1639152000,1639162800,96,487.0,...,9.872,11,1,AAL,AAL,EKYT,DK,2624887.0,Aalborg,Denmark

In [7]:
weather.columns

Index(['Unnamed: 0', 'rh', 'max_wind_spd_ts', 't_ghi', 'max_wind_spd',
       'solar_rad', 'wind_gust_spd', 'max_temp_ts', 'min_temp_ts', 'clouds',
       'max_dni', 'precip_gpm', 'wind_spd', 'slp', 'ts', 'max_ghi', 'temp',
       'pres', 'dni', 'dewpt', 'snow', 'dhi', 'precip', 'wind_dir', 'max_dhi',
       'ghi', 'max_temp', 't_dni', 'max_uv', 't_dhi', 'datetime',
       't_solar_rad', 'min_temp', 'max_wind_dir', 'snow_depth', 'iata_code',
       'latitude', 'longitude'],
      dtype='object')

In [8]:
weather_airport.shape

(86670, 46)

In [9]:
weather_airport.columns

Index(['rh', 'max_wind_spd_ts', 't_ghi', 'max_wind_spd', 'solar_rad',
       'wind_gust_spd', 'max_temp_ts', 'min_temp_ts', 'clouds', 'max_dni',
       'precip_gpm', 'wind_spd', 'slp', 'ts', 'max_ghi', 'temp', 'pres', 'dni',
       'dewpt', 'snow', 'dhi', 'precip', 'wind_dir', 'max_dhi', 'ghi',
       'max_temp', 't_dni', 'max_uv', 't_dhi', 'datetime', 't_solar_rad',
       'min_temp', 'max_wind_dir', 'snow_depth', 'iata_code_x', 'latitude',
       'longitude', 'id', 'gmt', 'iata_code_y', 'city_iata_code', 'icao_code',
       'country_iso2', 'geoname_id', 'airport_name', 'country_name'],
      dtype='object')

In [10]:
flight = pd.read_csv('./winter_2021_clean.csv')
flight.columns

Index(['flight_date', 'flight_status', 'departure_airport',
       'departure_timezone', 'departure_iata', 'departure_icao',
       'departure_gate', 'departure_delay', 'departure_scheduled',
       'departure_estimated', 'departure_actual', 'departure_estimated_runway',
       'departure_actual_runway', 'arrival_airport', 'arrival_timezone',
       'arrival_iata', 'arrival_icao', 'arrival_terminal', 'arrival_scheduled',
       'arrival_estimated', 'arrival_actual', 'arrival_estimated_runway',
       'arrival_actual_runway', 'airline_name', 'airline_iata', 'airline_icao',
       'flight_number', 'flight_iata', 'flight_icao'],
      dtype='object')

In [11]:
flight['departure_airport']

0           John F Kennedy International
1           John F Kennedy International
2           John F Kennedy International
3           John F Kennedy International
4           John F Kennedy International
                      ...
93495    Greater Rochester International
93496    Greater Rochester International
93497    Greater Rochester International
93498    Greater Rochester International
93499    Greater Rochester International
Name: departure_airport, Length: 93500, dtype: object

In [12]:
flight_weather = pd.merge(flight, weather_airport, how='inner', left_on=['flight_date', 'departure_airport'], 
                          right_on=['datetime', 'airport_name'])
flight_weather.head(20)

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_gate,departure_delay,departure_scheduled,departure_estimated,...,longitude,id,gmt,iata_code_y,city_iata_code,icao_code,country_iso2,geoname_id,airport_name,country_name
0,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
1,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
2,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
3,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
4,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
5,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
6,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
7,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
8,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
9,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,C10,10.0,2021-12-06 21:20:00+00:00,2021-12-06 21:20:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
10,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
11,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
12,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
13,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
14,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
15,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
16,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
17,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,4.763,268,1,AMS,AMS,EHAM,NL,6296680.0,Schiphol,Netherlands
18,2021-12-06,landed,Frankfurt International Airport,Europe/Berlin,FRA,EDDF,A40,14.0,2021-12-06 21:40:00+00:00,2021-12-06 21:40:00+00:00,...,8.571,2401,1,FRA,FRA,EDDF,DE,6290293.0,Frankfurt International Airport,Germany
19,2021-12-06,landed,Frankfurt International Airport,Europe/Berlin,FRA,EDDF,A40,14.0,2021-12-06 21:40:00+00:00,2021-12-06 21:40:00+00:00,...,8.571,2401,1,FRA,FRA,EDDF,DE,6290293.0,Frankfurt International Airport,Germany

In [13]:
flight_weather.shape

(56889, 75)

In [14]:
flight_weather.columns

Index(['flight_date', 'flight_status', 'departure_airport',
       'departure_timezone', 'departure_iata', 'departure_icao',
       'departure_gate', 'departure_delay', 'departure_scheduled',
       'departure_estimated', 'departure_actual', 'departure_estimated_runway',
       'departure_actual_runway', 'arrival_airport', 'arrival_timezone',
       'arrival_iata', 'arrival_icao', 'arrival_terminal', 'arrival_scheduled',
       'arrival_estimated', 'arrival_actual', 'arrival_estimated_runway',
       'arrival_actual_runway', 'airline_name', 'airline_iata', 'airline_icao',
       'flight_number', 'flight_iata', 'flight_icao', 'rh', 'max_wind_spd_ts',
       't_ghi', 'max_wind_spd', 'solar_rad', 'wind_gust_spd', 'max_temp_ts',
       'min_temp_ts', 'clouds', 'max_dni', 'precip_gpm', 'wind_spd', 'slp',
       'ts', 'max_ghi', 'temp', 'pres', 'dni', 'dewpt', 'snow', 'dhi',
       'precip', 'wind_dir', 'max_dhi', 'ghi', 'max_temp', 't_dni', 'max_uv',
       't_dhi', 'datetime', 't_solar_rad', 'min_temp', 'max_wind_dir',
       'snow_depth', 'iata_code_x', 'latitude', 'longitude', 'id', 'gmt',
       'iata_code_y', 'city_iata_code', 'icao_code', 'country_iso2',
       'geoname_id', 'airport_name', 'country_name'],
      dtype='object')

In [15]:
flight_weather = flight_weather.iloc[:, :-11]

In [16]:
flight_weather = pd.merge(flight_weather.loc[:, :], weather_airport, how='inner', left_on=['flight_date', 'arrival_airport'], 
                          right_on=['datetime', 'airport_name'], suffixes=('_departure', '_arrival'))
flight_weather.drop(flight_weather[-12:],axis=1)
flight_weather.head(10)

,flight_date,flight_status,departure_airport,departure_timezone,departure_iata,departure_icao,departure_gate,departure_delay,departure_scheduled,departure_estimated,...,longitude,id,gmt,iata_code_y,city_iata_code,icao_code,country_iso2,geoname_id,airport_name,country_name
0,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
1,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
2,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
3,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
4,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
5,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
6,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
7,2021-12-06,landed,Schiphol,Europe/Amsterdam,AMS,EHAM,B15,10.0,2021-12-06 21:25:00+00:00,2021-12-06 21:25:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
8,2021-12-06,landed,Frankfurt International Airport,Europe/Berlin,FRA,EDDF,A56,17.0,2021-12-06 21:40:00+00:00,2021-12-06 21:40:00+00:00,...,6.210,4579,1,LUX,LUX,ELLX,LU,6296718.0,Findel,Luxembourg
9,2021-12-06,landed,Frankfurt International Airport,Europe/Berlin,FRA,EDDF,B58,67.0,2021-12-06 12:25:00+00:00,2021-12-06 12:25:00+00:00,...,-68.364,6369,-4,PUJ,PUJ,MDPC,DO,3494242.0,Punta Cana International,Dominican Republic

In [17]:
flight_weather = flight_weather.iloc[:, :-11]
for i in flight_weather.columns:
    print(i)

flight_date
flight_status
departure_airport
departure_timezone
departure_iata
departure_icao
departure_gate
departure_delay
departure_scheduled
departure_estimated
departure_actual
departure_estimated_runway
departure_actual_runway
arrival_airport
arrival_timezone
arrival_iata
arrival_icao
arrival_terminal
arrival_scheduled
arrival_estimated
arrival_actual
arrival_estimated_runway
arrival_actual_runway
airline_name
airline_iata
airline_icao
flight_number
flight_iata
flight_icao
rh_departure
max_wind_spd_ts_departure
t_ghi_departure
max_wind_spd_departure
solar_rad_departure
wind_gust_spd_departure
max_temp_ts_departure
min_temp_ts_departure
clouds_departure
max_dni_departure
precip_gpm_departure
wind_spd_departure
slp_departure
ts_departure
max_ghi_departure
temp_departure
pres_departure
dni_departure
dewpt_departure
snow_departure
dhi_departure
precip_departure
wind_dir_departure
max_dhi_departure
ghi_departure
max_temp_departure
t_dni_departure
max_uv_departure
t_dhi_departure
datetime_departure
t_solar_rad_departure
min_temp_departure
max_wind_dir_departure
snow_depth_departure
iata_code_x_departure
rh_arrival
max_wind_spd_ts_arrival
t_ghi_arrival
max_wind_spd_arrival
solar_rad_arrival
wind_gust_spd_arrival
max_temp_ts_arrival
min_temp_ts_arrival
clouds_arrival
max_dni_arrival
precip_gpm_arrival
wind_spd_arrival
slp_arrival
ts_arrival
max_ghi_arrival
temp_arrival
pres_arrival
dni_arrival
dewpt_arrival
snow_arrival
dhi_arrival
precip_arrival
wind_dir_arrival
max_dhi_arrival
ghi_arrival
max_temp_arrival
t_dni_arrival
max_uv_arrival
t_dhi_arrival
datetime_arrival
t_solar_rad_arrival
min_temp_arrival
max_wind_dir_arrival
snow_depth_arrival
iata_code_x_arrival

In [18]:
flight_weather.loc[:, ['departure_iata', 'arrival_iata']]

      departure_iata arrival_iata
0                AMS          LUX
1                AMS          LUX
2                AMS          LUX
3                AMS          LUX
4                AMS          LUX
...              ...          ...
36402            ZRH          MUC
36403            ZRH          ARN
36404            ZRH          ARN
36405            SAP          MEX
36406            SAP          MEX

[36407 rows x 2 columns]

In [19]:
flight_weather = flight_weather.drop(['iata_code_x_departure', 'iata_code_x_arrival'], axis=1)

In [20]:
flight_weather.to_csv('./flight_weather.csv')